### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by acosano** [salveoo/voronmods#1]
Hi. I just was wondering if is OK with you if  I can do some modifications and adapt it to Euclid-Probe. The idea I have is to shorten the arm and have different holder adaptors for it. You could have one for Klicky, Magprobe , Euclid  etc...
I will acknowledge that the main idea and files comes from you and that I only add the changes for the Euclid. I also don't mind if you one to do the Euclid adapter.
Let me know what you think and sorry I could not find any other way to contact you if not opining a issue.

**Comment by salveoo** [comment]
Hey, it's a good idea to adapt it to different probes. You can contact me on discord salveo#6988 so we can work out some solutions.
