### ISSUE TITLE
Z endstop switch question

### ISSUE THREAD

**Issue by XEL-Maker** [salveoo/voronmods#2]
Hi I have a idea about Z endstop holde.
The reason for using the current z-endstop switch is that the probe is not attached to the extruder at first.
If the probe is attached to the extruder, wouldn't it be okay without a z-stop switch?
Currently, I have completed the chamber installation, so it is very difficult to install the z-endstop position.
Or, it would be nice to combine modeling with the lm guide stopper.

**Comment by salveoo** [comment]
You could use this probe as a virtual endstop but this requires the probe to be attached before homing. You can program the printer to get the probe when the print stops but as soon as you have a shutdown with the probe de attached you'll have to attach it manually. I don't think this is convenient in any way. Is it really that hard to bolt the Z endstop? Can't you pull the gantry up and screw it in place?

**Comment by XEL-Maker** [comment]
I did a simulation once and it was pretty hard.
If the gantry is raised, assembly is possible, but it is very difficult to align the z-endstop with the z-endstop triggered at that location when the z-endstop is installed.
https://github.com/salveoo/voronmods/blob/main/Switchwire%20Magprobe/readme.md#z-endstop-holder-1
There are no wires & acrylic wall (on the right side) in the photo here, but my Switchwire has it.
Disassembling the chamber can also be a solution, but it can cause a lot of things (I know the chamber is not completely sealed, but it's quite difficult to disassemble and reassemble).
Or, I think it might be faster to redesigning the LM stopper while using a virtual probe.
Another way is to shift the z-axis to the left. However, this leads to wiring complexity. This is because smps occupies its place.

**Comment by salveoo** [comment]
I redesigned the Z-endstop holder to trigger with the rail carriage. This endstop holder has a slot so you can adjust it by sliding it on the rail. Replace left z_carriage_stop with it. Way easier to mount. 
Let me know if you install it => https://github.com/salveoo/voronmods/blob/main/Switchwire%20Magprobe/STL/SW_stock/z_endstop_stock_rail.stl

<p align="center">
  <img width="550" src="https://user-images.githubusercontent.com/44800440/155617358-907fa32b-e0d8-4e9b-91dc-c7842198092e.png">
</p>

<p align="center">
  <img width="550" src="https://user-images.githubusercontent.com/44800440/155617418-5cadc7bf-eb1e-4c1a-9e73-70ce7ef0bc62.png">
</p>

**Comment by XEL-Maker** [comment]
Thank you so much for redesigning the Z-endstop holder.
I will apply it as soon as possible.
I will close this issue unless there is a problem.
