### ISSUE TITLE
servo arm original dimension

### ISSUE THREAD

**Issue by XEL-Maker** [salveoo/voronmods#7]
Hi!
 I want to get the original cad file of servo arm for build euclid probe.

I used this mode until recently, but errors often occurred in mesh measurements due to poor contact.
I decided to change it to Euclidean probe, but I considered the problem of receiving the probe, and as a result, I thought it would be possible to change the servo_arm.

**Comment by salveoo** [comment]
Hi! You can find the cad here: https://github.com/salveoo/voronmods/tree/main/Switchwire%20Magprobe/CAD .

**Comment by XEL-Maker** [comment]
Thanks a lot i'll try to build.
